import { AxiosResponse } from 'axios'
// Generated by https://quicktype.io
export interface LoginResponse {
  status?: string
  current?: string
  access_token?: string
  expires_in?: number
  message?: string
}
